(function(g){var window=this;'use strict';var Sqb=function(a){g.V.call(this,{I:"div",S:"ytp-inline-preview-ui"});this.og=!1;this.player=a;this.T(a,"onStateChange",this.XR);this.T(a,"videodatachange",this.yx);this.T(a,"onInlinePreviewModeChange",this.s7);this.yf=new g.zu(this.Fw,null,this);g.L(this,this.yf)},F6=function(a){g.vV.call(this,a);
this.j=new Sqb(this.player);g.L(this,this.j);this.j.hide();g.oU(this.player,this.j.element,4);a.isInline()&&(this.load(),a=a.getRootNode(),g.Ku(a,["ytp-inline-preview-mode","ytp-no-contextmenu"]))};
g.w(Sqb,g.V);g.k=Sqb.prototype;
g.k.HO=function(){this.tooltip=new g.NX(this.player,this);g.L(this,this.tooltip);g.oU(this.player,this.tooltip.element,4);this.tooltip.scale=.6;this.Tc=new g.ZV(this.player);g.L(this,this.Tc);this.yk=new g.V({I:"div",Ma:["ytp-inline-preview-scrim"]});g.L(this,this.yk);this.yk.Da(this.element);this.T(this.yk.element,"click",this.yJ);this.Gj=new g.GX(this.player,this,300);g.L(this,this.Gj);this.Gj.Da(this.yk.element);this.controls=new g.V({I:"div",S:"ytp-inline-preview-controls"});g.L(this,this.controls);
this.controls.Da(this.element);var a=new g.YW(this.player,this,!1);g.L(this,a);a.Da(this.controls.element);a=new g.EX(this.player,this);g.L(this,a);a.Da(this.controls.element);this.Oc=new g.eX(this.player,this);g.L(this,this.Oc);g.oU(this.player,this.Oc.element,4);this.T(this.player,"appresize",this.Hb);this.T(this.player,"fullscreentoggled",this.Hb);this.Hb()};
g.k.show=function(){g.Au(this.yf);this.og||(this.HO(),this.og=!0);0!==this.player.getPlayerState()&&g.V.prototype.show.call(this);this.Oc.show();this.player.Qa("onInlinePreviewUiReady")};
g.k.hide=function(){this.yf.stop();g.V.prototype.hide.call(this);this.player.isInline()||this.og&&this.Oc.hide()};
g.k.ya=function(){g.V.prototype.ya.call(this)};
g.k.yJ=function(a){a.target===this.yk.element&&this.player.Qa("onExpandInlinePreview",a)};
g.k.s7=function(){g.Nu(this.player.getRootNode(),"ytp-inline-preview-mode",this.player.isInline())};
g.k.Xe=function(){this.Oc.Ec();this.Gj.Ec()};
g.k.Fw=function(){this.Xe();g.Au(this.yf)};
g.k.Hb=function(){g.qX(this.Oc,0,this.player.kb().getPlayerSize().width,!1);g.fX(this.Oc)};
g.k.XR=function(a){this.player.isInline()&&(0===a?this.hide():this.show())};
g.k.yx=function(a,b){if(this.player.isInline()){g.Nu(this.player.getRootNode(),"ytp-show-inline-preview-audio-controls",b.tC);var c,d,e;a=!(null==(e=null==(c=b.getPlayerResponse())?void 0:null==(d=c.playerConfig)?void 0:d.inlinePlaybackConfig)||!e.showScrubbingControls);g.Nu(this.player.getRootNode(),"ytp-hide-inline-preview-progress-bar",!a)}};
g.k.Jd=function(){return this.tooltip};
g.k.Yf=function(){return!1};
g.k.Kf=function(){return!1};
g.k.Yj=function(){return!1};
g.k.tB=function(){};
g.k.vp=function(){};
g.k.Ns=function(){};
g.k.xn=function(){return null};
g.k.IH=function(){return null};
g.k.YN=function(){return new g.te(0,0)};
g.k.Sk=function(){return new g.Sr(0,0,0,0)};
g.k.handleGlobalKeyDown=function(){return!1};
g.k.handleGlobalKeyUp=function(){return!1};
g.k.Dr=function(a,b,c,d,e){var f=d=0,h=0,l=g.fs(a);if(b){c=g.Iu(b,"ytp-mute-button");var m=g.Iu(b,"ytp-subtitles-button"),n=g.ds(b,this.element);b=g.fs(b);d=n.y+40;if(m||c)h=n.x-l.width+b.width}else h=c-l.width/2,f=35;b=this.player.kb().getPlayerSize().width;h=g.le(h,0,b-l.width);d?(a.style.top=d+(e||0)+"px",a.style.bottom=""):(a.style.top="",a.style.bottom=f+"px");a.style.left=h+"px"};
g.k.showControls=function(){};
g.k.kq=function(){};
g.k.Rj=function(){return!1};
g.k.mu=function(){};
g.k.Lr=function(){};
g.k.Dm=function(){};
g.k.Cm=function(){};
g.k.Aq=function(){};
g.k.xp=function(){};
g.k.ax=function(){};
g.k.JH=function(){return null};g.w(F6,g.vV);F6.prototype.Dl=function(){return!1};
F6.prototype.load=function(){this.player.hideControls();this.j.show()};
F6.prototype.unload=function(){this.player.showControls();this.j.hide()};g.uV("inline_preview",F6);})(_yt_player);
